name: Test

on:
  repository_dispatch:
    types: [repository-dispatch-test]

jobs:
  Repository-Dispatch-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # job全体
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
      # - run: echo ${{ secrets.SECRET_HOGE }}
